spring:
    ai:
      azure:
        openai:
          api-key: 8aac9a0f0abd40fa9723d130ae40d1e7
azure:
  formrecognizer:
    key: 6MD2eADL0MSJDP59O8sCY5Ggq0KCsr26DxaXL1y2DX2p8KK9ziGgJQQJ99AKACYeBjFXJ3w3AAALACOGK1M2
  search:
    key: 6Fw7mADRnYUls11jf2YJ3EpJxAnd8bJwVwO9pVeQQwAzSeBmw6lx
